spring:
  profiles:
    active: dev
  #  messages:
  #    basename: i18n/messages
  thymeleaf:
    cache: false
  mvc:
    favicon:
      enabled: false
#    prefix: classpath:/templates
#    suffix: .html
#    mode: HTML

Comment:
  avatar: /img/xys.jpg
